In [81]:
import numpy as np

In [82]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder


In [83]:
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam


In [84]:
iris_data = load_iris() 

In [85]:
print('Example data: ')
print(iris_data.data[:5])
print('Example labels: ')
print(iris_data.target[:5])


Example data: 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
Example labels: 
[0 0 0 0 0]


In [86]:
x = iris_data.data
y_ = iris_data.target.reshape(-1, 1) 


In [87]:
encoder = OneHotEncoder(sparse=False)
y = encoder.fit_transform(y_)

In [88]:
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.20)


In [89]:
model = Sequential()

model.add(Dense(10, input_shape=(4,), activation='relu', name='fc1'))
model.add(Dense(10, activation='relu', name='fc2'))
model.add(Dense(3, activation='softmax', name='output'))


In [90]:
optimizer = Adam(lr=0.001)
model.compile(optimizer, loss='categorical_crossentropy', metrics=['accuracy'])


C:\Users\RASHMI\anaconda3\lib\site-packages\tensorflow\python\keras\optimizer_v2\optimizer_v2.py:374: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  warnings.warn(


In [91]:
print('Neural Network Model Summary: ')
print(model.summary())


Neural Network Model Summary: 
Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
fc1 (Dense)                  (None, 10)                50        
_________________________________________________________________
fc2 (Dense)                  (None, 10)                110       
_________________________________________________________________
output (Dense)               (None, 3)                 33        
Total params: 193
Trainable params: 193
Non-trainable params: 0
_________________________________________________________________
None


In [105]:
model.fit(train_x, train_y, verbose=2, batch_size=5, epochs=200)


Epoch 1/200
24/24 - 0s - loss: 0.0598 - accuracy: 0.9667
Epoch 2/200
24/24 - 0s - loss: 0.0575 - accuracy: 0.9750
Epoch 3/200
24/24 - 0s - loss: 0.0611 - accuracy: 0.9750
Epoch 4/200
24/24 - 0s - loss: 0.0660 - accuracy: 0.9750
Epoch 5/200
24/24 - 0s - loss: 0.0566 - accuracy: 0.9833
Epoch 6/200
24/24 - 0s - loss: 0.0620 - accuracy: 0.9667
Epoch 7/200
24/24 - 0s - loss: 0.0599 - accuracy: 0.9833
Epoch 8/200
24/24 - 0s - loss: 0.0583 - accuracy: 0.9750
Epoch 9/200
24/24 - 0s - loss: 0.0613 - accuracy: 0.9750
Epoch 10/200
24/24 - 0s - loss: 0.0579 - accuracy: 0.9833
Epoch 11/200
24/24 - 0s - loss: 0.0699 - accuracy: 0.9750
Epoch 12/200
24/24 - 0s - loss: 0.0579 - accuracy: 0.9750
Epoch 13/200
24/24 - 0s - loss: 0.0661 - accuracy: 0.9667
Epoch 14/200
24/24 - 0s - loss: 0.0635 - accuracy: 0.9833
Epoch 15/200
24/24 - 0s - loss: 0.0695 - accuracy: 0.9750
Epoch 16/200
24/24 - 0s - loss: 0.0766 - accuracy: 0.9583
Epoch 17/200
24/24 - 0s - loss: 0.0625 - accuracy: 0.9833
Epoch 18/200
24/24 - 0s

Epoch 142/200
24/24 - 0s - loss: 0.0636 - accuracy: 0.9750
Epoch 143/200
24/24 - 0s - loss: 0.0577 - accuracy: 0.9833
Epoch 144/200
24/24 - 0s - loss: 0.0766 - accuracy: 0.9667
Epoch 145/200
24/24 - 0s - loss: 0.0613 - accuracy: 0.9833
Epoch 146/200
24/24 - 0s - loss: 0.0590 - accuracy: 0.9750
Epoch 147/200
24/24 - 0s - loss: 0.0566 - accuracy: 0.9750
Epoch 148/200
24/24 - 0s - loss: 0.0568 - accuracy: 0.9833
Epoch 149/200
24/24 - 0s - loss: 0.0700 - accuracy: 0.9667
Epoch 150/200
24/24 - 0s - loss: 0.0628 - accuracy: 0.9833
Epoch 151/200
24/24 - 0s - loss: 0.0573 - accuracy: 0.9833
Epoch 152/200
24/24 - 0s - loss: 0.0564 - accuracy: 0.9833
Epoch 153/200
24/24 - 0s - loss: 0.0563 - accuracy: 0.9750
Epoch 154/200
24/24 - 0s - loss: 0.0585 - accuracy: 0.9750
Epoch 155/200
24/24 - 0s - loss: 0.0567 - accuracy: 0.9667
Epoch 156/200
24/24 - 0s - loss: 0.0624 - accuracy: 0.9583
Epoch 157/200
24/24 - 0s - loss: 0.0582 - accuracy: 0.9750
Epoch 158/200
24/24 - 0s - loss: 0.0630 - accuracy: 0.97

In [102]:
results = model.evaluate(test_x, test_y)


1/1 [==============================] - 0s 15ms/step - loss: 0.0277 - accuracy: 1.0000


In [103]:
print('Final test set loss: {:4f}'.format(results[0]))
print('Final test set accuracy: {:4f}'.format(results[1]))

Final test set loss: 0.027744
Final test set accuracy: 1.000000
